services:
  postgres:
    image: postgres:17-alpine
    container_name: conferencehub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      Jwt__Key: ${JWT_KEY}
    ports:
      - "5434:5432"
    volumes:
      - conferencehub-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  conferencehub-postgres-data:
